project_name: sensibo-timer-guard

builds:
- env: [CGO_ENABLED=0]
  targets:
    - windows_amd64
    - darwin_amd64
    - darwin_arm64
    - linux_amd64
    - linux_arm64
    - linux_arm_6
    - linux_arm_7

dockers:

- image_templates: ["slygon/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  goos: linux
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/elig-salt/go-{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/elig-salt/go-{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2021-12-12T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

- image_templates: ["slygon/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goos: linux
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/elig-salt/go-{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/elig-salt/go-{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2021-12-12T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

- image_templates: ["slygon/{{ .ProjectName }}:{{ .Version }}-armv7"]
  dockerfile: Dockerfile
  goos: linux
  goarch: arm
  goarm: "7"
  use: buildx
  build_flag_templates:
  - --platform=linux/arm/v7
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/elig-salt/go-{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/elig-salt/go-{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2021-12-12T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT


- image_templates: ["slygon/{{ .ProjectName }}:{{ .Version }}-armv6"]
  dockerfile: Dockerfile
  goos: linux
  goarch: arm
  goarm: "6"
  use: buildx
  build_flag_templates:
  - --platform=linux/arm/v6
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/elig-salt/go-{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/elig-salt/go-{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2021-12-12T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

docker_manifests:

- name_template: slygon/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - slygon/{{ .ProjectName }}:{{ .Version }}-amd64
  - slygon/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - slygon/{{ .ProjectName }}:{{ .Version }}-armv7
  - slygon/{{ .ProjectName }}:{{ .Version }}-armv6

- name_template: slygon/{{ .ProjectName }}:latest
  image_templates:
  - slygon/{{ .ProjectName }}:{{ .Version }}-amd64
  - slygon/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - slygon/{{ .ProjectName }}:{{ .Version }}-armv7
  - slygon/{{ .ProjectName }}:{{ .Version }}-armv6

# archives:
#   - format: tar.gz
#     replacements:
#       darwin: Darwin
#       linux: Linux
#       windows: Windows
#       386: i386
#       amd64: x86_64
#     format_overrides:
#       - goos: windows
#         format: zip
#     name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}{{.Arm}}'
#     files:
#       - "README.md"


checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
